'use strict';
const campaignEditorial={
 kai:{name:'KAI',title:'捕获坐骑，种植饲料。',headline:'捕获坐骑，亲手养出一支机动队',intro:'从利贝拉的村庄出发，凯伊与蒂亚拉、彼得走向帝都，也一步步接近自己的身世。沿途看见的动物和空地都能成为队伍的助力：捕来坐骑、照料成长，再用栽培补足饲料。喜欢边探索边养队，这一篇有很多值得绕路的地方。',team:'凯伊冲锋，彼得远射，蒂亚拉守住回复',investment:'先把击杀和武器训练分给凯伊、彼得；蒂亚拉优先白魔术，古扎岚负责补剑系输出。名声4的诺克裘拉可补格斗，名声5的马吉迪与米迦艾拉选一位补斧手。杨界虽只需名声3，但已有蒂亚拉时，治疗位并不一定还缺人。',timing:'把捕获的等待回合与采集、送礼一起安排。想培养骑兵，先照料实际要用的坐骑；别把饲料分散给所有动物。',tags:['捕获与饲育','栽培补给','机动养成']},
 theodora:{name:'THEODORA',title:'招募军团，调度战备。',headline:'把军团编进队伍，让派兵支撑战备',intro:'年轻的萨拉米斯女王来到帝都，身边既有忠心的旧部，也有各怀心思的新同伴。赛奥朵拉篇让你亲自安排这支队伍的后勤与战术：招募军团兵、配备计略，把探索所得交给波拿帕尔特换成战备收入。女王能站在前线，整支军团也能一起成长。',team:'女王与重装守线，魔法和弓箭打开缺口',investment:'赛奥朵拉、波拿帕尔特和莉利安分别负责前排、魔法与远程。索绯雅先保回复，莱桑达负责机动。想加近战输出，名声3看诺克裘拉，名声4看能砍价到10G的札可捏；需要灵活剑手再看洛蕾塔，不必把原有重装全部换掉。',timing:'提高名声既影响人物招募，也改善军团募集与派兵能力。先留够出战的军团兵，再把富余部队派去采集，避免开战时常用编配空缺。',tags:['军团兵与计略','探索派兵','战备增援']},
 leda:{name:'LEDA',title:'酒馆献艺，咒歌助战。',headline:'用兴行积攒名声，把咒歌带上战场',intro:'故乡被毁之后，蕾达循着仇人的线索来到帝都。她在酒馆与村镇献艺，得到的不只是报酬：新的咒歌、秘密地点与舞者资格，会改变这支队伍的战斗方式。穆与巴卡尼亚顶住正面，蕾达则能决定，是自己出手，还是把下一次行动交给同伴。',team:'穆与巴卡尼亚顶住正面，蕾达决定下一步',investment:'穆负责稳定的物理击杀，巴卡尼亚承伤，西洛可先兼顾回复；奥林匹亚加入后让她接手治疗。古扎岚门槛低，但和卡塔妮雅同为剑位，按需要挑一位主练。第7章可补弓手基罗伊卡；想补法术伤害，提前准备菲亚娜的3000G。',timing:'先看兴行的期限，再把演出地点与招募路线排在一起。名声4的基罗伊卡、贾斯敏都要到第7章才出现；前期不要为了他们额外空等。',tags:['兴行与咒歌','秘密地点','舞者再行动']}
};
function campaignFigure(asset,alt,kicker,title,body,page){return `<figure class="di-feature"><a class="di-image" href="assets/campaign/${asset}.webp" target="_blank" rel="noopener" aria-label="放大${esc(alt)}"><img src="assets/campaign/${asset}.webp" alt="${esc(alt)}" loading="lazy"><span>查看大图 ↗</span></a><figcaption><span class="di-kicker">${kicker}</span><h3>${title}</h3>${body}<small>日文版游戏画面 · <a href="https://game8.jp/fe-banshisenko/${page}" target="_blank" rel="noopener noreferrer">Game8 来源 ↗</a></small></figcaption></figure>`;}
function campaignSystems(id){
 if(id==='kai')return campaignFigure('capture','选择饲料引诱动物的菜单','第 5 章 / 捕获与饲育','先找到动物，再准备它喜欢的饲料','<p>在世界地图找到动物图标，进入地点后选择引诱，放入符合喜好的饲料；经过几个自由行动回合，再回来尝试捕获。放好饲料并不代表一定成功。</p><p>捕到后去<strong>鞑古席翁的厩舍</strong>管理、喂食。提高友好等级可以取得骑乘技能；高友好坐骑也有培养收益。动物要配给能骑乘的兵种，才能发挥作用。</p><p>先看动物菜单的食材与口味偏好，不要把马喜欢的蔬菜直接喂给所有种类。</p>','816904')+campaignFigure('cultivation','选择植物进行栽培的菜单','第 6 章 / 栽培','在常走的路上，留一块补给田','<p>找地图上的白色五边形空地，选择栽培，使用手里已有的植物开始种植。经过回合成熟后，路过就能收获。</p><p>肥料可提高稀有收获的机会；一块田收获若干次后会恢复为空地，需要重新种。用常用饲料作物起步，顺路收成，比来回赶路更省行动。</p>','816933')+`<ol class="di-loop"><li><b>捕获</b><span>动物地点 · 喜好饲料</span></li><li><b>照料</b><span>帝都厩舍 · 提高友好</span></li><li><b>补给</b><span>空地栽培 · 顺路收获</span></li></ol>`;
 if(id==='theodora')return campaignFigure('legion','战斗中的计略范围与目标','第 4 章 / 配备与计略','先配给角色，战斗中才能下令','<p>打开<strong>整备 → 军团兵配备</strong>，按角色需要选择能力加成与计略。军团兵不只配给女王，其他同伴也能使用。</p><p>出战后选择计略。攻击计略不会受到反击，适合安全削弱危险敌人；但使用次数有限，先看作用范围与目标再下令。</p>','817104')+campaignFigure('recruit-legion','地图据点中的兵士募集菜单','第 5—8 章 / 募集与后勤','多招一队兵，也能多一队人采集','<p><strong>第5章：</strong>探索地点可派军团兵采集，经过回合取得素材；派出期间不能拿同一队做其他事。回据点找波拿帕尔特，查看战备增援要交什么，再安排采集。</p><p><strong>第6章：</strong>在城镇据点募集士兵，等待回合集结；应援演说可提高高阶军团出现机会。第8章的兵士大募集自带演说效果。</p><p><strong>第7章：</strong>多余军团可交军兵输送长，积累兵备值换战术指南书。先保留常用计略和采集班底，再处理富余。</p>','817104')+`<ol class="di-loop"><li><b>募集</b><span>地图城镇 · 等待集结</span></li><li><b>派兵</b><span>探索地点 · 收集素材</span></li><li><b>交付</b><span>波拿帕尔特 · 战备收入</span></li></ol><p class="di-editor-note"><a href="https://game8.jp/fe-banshisenko/816792" target="_blank" rel="noopener noreferrer">战备增援与路线说明 · Game8 ↗</a></p>`;
 return campaignFigure('performance','向酒馆店主接取兴行委托','第 4 章 / 酒馆与地方兴行','先接演出，再把报酬变成战力','<p>到<strong>鞑古席翁南侧酒馆</strong>找店主。地方兴行要在期限内赶到指定地点演出，取得钱、素材与名声，也可能得知秘密地点。</p><p>酒馆兴行则要满足指定名声、交齐素材，再回店主处报告。报酬可解锁蕾达的<strong>咒歌</strong>，也会逐步开放饮品兑换。</p><p>咒歌属于蕾达的烈焰技，不同招式可强化同伴或召唤魔兽。看清效果再选，不能把所有咒歌都当成直接伤害。</p>','816915')+`<div class="di-upgrade campaign-dancer"><span class="di-kicker">第 9 章 / 舞者的继承者</span><h3>让同伴再行动一次，比自己多打一刀更有用的时候</h3><p>完成第9章开场对话后，到<strong>帝都上层游兴区</strong>接取「舞者的继承者」。期限为<strong>1449年10月15日</strong>；不要等到离开第一部再补。</p><ol class="di-upgrade-steps"><li><b>1</b><div><h4>取回委托物</h4><p>到拜纳绿洲市场购买任务指定植物 ×1，1050G；也可探索取得。日文来源名「ヒンガシャ」，请按任务标记核对，避免买错同类素材。</p></div></li><li><b>2</b><div><h4>回报，取得舞姬项链</h4><p>完成委托后开放舞者资格。蕾达准备剑术B或弓术B，再到资格考试处办理转职。</p></div></li><li><b>3</b><div><h4>把行动交给当前最需要的人</h4><p>舞者的「跳舞」让选中的同伴再行动一次：补一次治疗、追加击杀或调整站位。第一部限定蕾达，第三部才开放给其他角色。</p></div></li></ol><p class="di-editor-note"><a href="https://gamewith.jp/fefw/578950" target="_blank" rel="noopener noreferrer">委托地点、期限与资格 · GameWith ↗</a></p></div>`;
}
function campaignPortal(s){
 const p=s.profile.pilot,e=campaignEditorial[s.id],hero=routeCharacter(s.title.replace('路线','')),route=s.title.replace('路线','线'),recruits=dietrichRecruits(s.id);
 const sections=[['overview','本篇独有玩法'],['team','原生队伍培养'],['strength','招募与训练顺序'],['recruit','名声招募金字塔'],['paralogues','外传与漏接提醒'],['classes','兵种选择与解锁'],['notes','本篇注意事项']];
 return `<article class="route-portal di-pilot campaign-pilot" data-theme="${esc(s.profile.theme)}"><header class="route-hero"><div class="container route-hero-inner"><div class="route-hero-copy"><a class="route-back" href="#story">← 全部人物篇章</a><div class="eyebrow">${e.name} · 第一部 / ${esc(s.profile.faction)}</div><h1>${esc(s.title.replace('路线','篇'))}<span>${e.title}</span></h1><p>${dietrichText(e.intro)}</p><div class="route-hero-tags">${e.tags.map(t=>`<span>${t}</span>`).join('')}</div><a class="button gold" href="#route/${s.id}/overview">看本篇独有玩法 ↓</a></div><div class="route-hero-art"><div class="route-ring" aria-hidden="true"></div><img src="${esc(hero.portrait)}" alt="${esc(hero.name)}人物立绘"><span class="route-hero-name" aria-hidden="true">${e.name}</span></div></div></header><div class="container"><nav class="route-switch" aria-label="切换人物篇章">${D.story.filter(x=>x.part===1).map(x=>`<a href="${storyLink(x)}" ${s.id===x.id?'aria-current="page"':''}>${esc(x.title.replace('路线','篇'))} ↗</a>`).join('')}<a href="#story/war">第二部 · 战争篇 →</a></nav><div class="route-editorial"><nav class="route-toc" aria-label="本篇目录"><span class="eyebrow">${e.name} / FIELD NOTES</span>${sections.map(([id,label],i)=>`<a href="#route/${s.id}/${id}" data-section="${id}"><span>0${i+1}</span>${label}</a>`).join('')}</nav><div class="route-content">
 <section id="overview" class="route-section">${routeSectionHead('01','A WAY OF YOUR OWN',e.headline)}${campaignSystems(s.id)}${evidence(p.sources)}</section>
 <section id="team" class="route-section">${routeSectionHead('02','YOUR COMPANY',e.team,'剧情与教学队友单独列出。箭头是培养方向，不要求练满每个职业；仍须满足进度、技能与考试条件。')}<div class="di-team-strip">${p.native.map(n=>`<a href="#route/${s.id}/member-${routeCharacter(n.name).id}"><img src="${esc(routeCharacter(n.name).avatar)}" alt=""><strong>${esc(n.name)}</strong><small>${esc(n.role)}</small></a>`).join('')}</div><div class="di-plans">${p.native.map(n=>`<div id="member-${routeCharacter(n.name).id}" class="di-anchor">${dietrichPlan(n)}</div>`).join('')}</div></section>
 <section id="strength" class="route-section">${routeSectionHead('03','TRAINING & TIMING','先养眼前的主力，再为下一个缺口招人')}<div class="di-picks"><h3>本篇资源优先给谁</h3><p>${dietrichText(e.investment)}</p><small>按本线成本与队伍职能给出的编辑建议，不是全角色强度排名。</small></div><div class="di-growth"><div><span>尽早加入</span><h3>更早决定兵种与技能</h3><p>想长期培养的人，出现且条件达标后即可安排入队。实际入队等级越低，后续能由你选择兵种的升级次数通常越多。</p></div><div><span>名声不是出现日期</span><h3>门槛、时点、交涉要一起看</h3><p>低名声不保证低等级，也不保证前几章就能遇见。金字塔列的是门槛，人物卡还会单列出现时间与附加条件。</p></div></div><p class="route-lead">${dietrichText(e.timing)}</p></section>
 <section id="recruit" class="route-section">${routeSectionHead('04','RENOWN & RECRUITMENT','按名声找人，按队伍缺口做选择','先看全线分层，再读名声3—6的培养卡。教学加入的同伴在上方介绍，不重复放入金字塔。')}${dietrichPyramid(recruits,s.id)}<div class="di-fame-nav"><a href="#route/${s.id}/fame-low"><b>3—5</b><span>低门槛候选</span></a><a href="#route/${s.id}/fame-mid"><b>6</b><span>中段补位</span></a><a href="#route/${s.id}/fame-all"><b>全线</b><span>招募条件表</span></a></div>${[[true,'fame-low','名声 3—5 · 先准备这些人'],[false,'fame-mid','名声 6 · 看缺口再投入']].map(([low,id,title])=>`<div id="${id}" class="di-anchor"><h3 class="di-band">${title}</h3><div class="di-plans">${p.scouts.filter(n=>low?n.fame<=5:n.fame===6).map(n=>dietrichPlan(n)).join('')}</div></div>`).join('')}
 <details id="fame-all" class="all-recruits di-anchor"><summary>本线完整招募条件 · ${recruits.length} 位，按名声升序 <span>＋</span></summary><p class="notice">S＝支援，R＝名声。不含上方剧情与教学同伴；未展开的交涉条件不表示没有要求。</p><div class="route-recruit-list">${recruits.map(({c,fame})=>{const n=p.scouts.find(n=>n.name===c.name);return `<div data-recruit-fame="${fame}"><span class="di-list-fame">名声 ${fame}</span>${dietrichPerson(c.name)}<p>${n?`支援 ${n.support} · ${esc(n.condition)}<small>${esc(n.arrival)}</small>`:esc(c.recruit[route])}</p><span class="tag ${n?'green':''}">${n?'本线详页已核对':'继承条目'}</span></div>`;}).join('')}</div></details></section>
 ${paralogueSection(s.id)}${routeClassSection(s.id)}
 <section id="notes" class="route-section">${routeSectionHead('07','BEFORE YOU MOVE ON','离开本篇前，再检查一次')}<ol class="route-cautions">${s.profile.notes.map(n=>`<li>${dietrichText(n)}</li>`).join('')}<li>其他三位主角不能招进本篇；外传相遇与第三部加入是不同条件。</li><li>第一部收尾前，把需要的装备与道具带在角色身上，完成想要的招募和限时请求。</li></ol></section><div class="route-ending"><div><span class="eyebrow">PART II</span><h2>带上培养好的同伴，走进战争篇。</h2></div><a class="button" href="#story/war">第二部 · 战争篇 →</a></div></div></div></div></article>`;
}
function laterPartOpening(s){
 const war=s.part===2;
 return `<header class="part-opening ${war?'part-war':'part-salvation'}"><div class="container part-opening-inner"><div class="part-opening-copy"><a class="route-back" href="#story">← 全部篇章</a><div class="eyebrow">PART ${war?'II · THE WAR':'III · SALVATION'}</div><h1>${war?'战争篇':'救世篇'}</h1><h2>${war?'整备之后，战线向前。':'重聚同伴，重建失落的大地。'}</h2><p>${war?'四位主角的旅途在战争中走向共同的战场。第一部带来的队伍、装备与培养，会成为接下来连续作战的底气。先弄清补给与整备规则，再出发。':'救世主再度踏上鞑古席翁。四条旅途中结下的缘分，将陆续回到队伍；从一队人的战斗，到多支部队的防卫、复兴与远征。'}</p><div class="route-hero-tags">${(war?['六章连续作战','每章整备','条件角色加入']:['同伴重聚','神殿复兴','多队调度']).map(t=>`<span>${t}</span>`).join('')}</div><a class="button gold" href="#story/${s.id}/${war?'war-systems':'part-notes'}">${war?'先看系统变化':'进入本篇准备'} ↓</a></div><figure class="part-opening-art">${war?`<div class="war-portraits">${['凯伊','迪托利希','赛奥朵拉','蕾达'].map(n=>`<img src="${esc(routeCharacter(n).portrait)}" alt="${n}立绘">`).join('')}</div><figcaption>四位主角 · 各自带领本线队伍进入战争篇</figcaption>`:`<a href="assets/campaign/salvation-opening.webp" target="_blank" rel="noopener"><img src="assets/campaign/salvation-opening.webp" alt="救世主在鞑古席翁的开场游戏画面"></a><figcaption>救世篇开场 · <a href="https://game8.jp/fe-banshisenko/817161" target="_blank" rel="noopener noreferrer">Game8 日文版画面 ↗</a></figcaption>`}</figure></div></header>${war?warIntroduction():`<section id="part-notes" class="container part-intro"><div class="section-heading"><div><div class="eyebrow">A NEW CAMPAIGN</div><h2>先重聚，再分队</h2></div></div><p class="route-lead">第一区分的援军登场，不等于已经完成永久入队。进入第二区分的自由行动后，逐个与符合条件的同伴交谈，再安排培养和神殿复兴。后续多队行动时，给每队留回复与处理不同敌人的手段。</p><p>下方战斗与剧情细节保持折叠，需要时再按区分阅读。</p>${evidence(s.sources)}</section>`}`;
}
function warIntroduction(){return `<section id="war-systems" class="container part-intro"><div class="section-heading"><div><div class="eyebrow">WHAT CHANGES IN PART II</div><h2>从自由探索，转为「整备 → 行军 → 战斗」</h2></div></div><div class="war-system-grid"><article><span>01 / 行动</span><h3>没有第一部的自由逛图</h3><p>每章先在据点整备，再进入战斗。资格考试、祝福与白鸦等功能仍可用，但不能再靠自由探索补招募与素材。</p></article><article><span>02 / 成长</span><h3>军行动，每章三选一</h3><p>兵力训练、全军技能训练、全员奉仕活动，只能选一项。按当前最缺的是等级、技能还是加护来决定。</p></article><article><span>03 / 武器</span><h3>没有商店，未损坏武器会修复</h3><p>每章有铁制武器、调合药与解毒药补给。过章时仍未损坏的武器恢复耐久；不要把强力武器用到损坏，再指望自动修好。</p></article><article><span>04 / 转职</span><h3>考试凭证补到5个，不是每章加5个</h3><p>初级、中级、上级考试凭证会补至5个。条件已满足的队员，可在据点完成考试；技能不足仍需训练。</p></article></div><div class="war-departure"><div><span class="eyebrow">BEFORE DEPARTURE</span><h2>最后一次自由行动，优先办这四件事</h2><p>入队、装备、技能与限时委托，都在第一部检查。</p></div><ol><li><strong>把装备带在身上。</strong>第二部只能使用角色携带过去的武器与道具；仓库内容留到第三部再处理。</li><li><strong>先购买、锻造常用武器。</strong>准备特效武器、魔法武器和必要消耗品，第二部不能逛商店或铁匠铺补买。</li><li><strong>收好想培养的人，补技能与资格。</strong>提前完成主力训练、祝福和加护准备，进入连续作战后不容易临时补课。</li><li><strong>小迪、蕾达线留意「亡妹的首饰」。</strong>第一部请求是后续基里克（キリーク）、内森（ネイサン）的条件加入的前置；还要满足第二部的指定战斗条件，不能只打通章节。</li></ol></div><p class="di-editor-note">第二部剧情与战场大体共通，携带的队伍和条件角色则取决于前一篇的准备。下方按章列出已核对的推进笔记。</p>${evidence([{url:'https://gamewith.jp/fefw/577891',label:'GameWith · 战争篇系统、补给与继承'},{url:'https://game8.jp/fe-banshisenko/817090',label:'Game8 · 战争篇准备与注意事项'}])}</section>`;}
