'use strict';
// Shared editorial building blocks; Dietrich remains the reference route.
function dietrichData(routeId='dietrich'){return D.story.find(s=>s.id===routeId).profile.pilot;}
function dietrichPerson(name){
  const c=routeCharacter(name);if(!c)return esc(name);
  return `<button class="di-person" data-character="${esc(c.id)}">${c.avatar?`<img src="${esc(c.avatar)}" alt="" loading="lazy">`:''}<span>${esc(c.name)}</span></button>`;
}
function dietrichText(text){
  const names=D.characters.map(c=>c.name).sort((a,b)=>b.length-a.length);
  const pattern=new RegExp('('+names.map(n=>n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')','g');
  return String(text||'').split(pattern).map(part=>names.includes(part)?dietrichPerson(part):esc(part)).join('');
}
function dietrichRecruits(routeId='dietrich'){
  const story=D.story.find(s=>s.id===routeId),route=story.title.replace('路线','线');
  const native=new Set(dietrichData(routeId).native.map(n=>n.name));
  return D.characters.filter(c=>c.recruit[route]&&c.recruit[route]!=='—'&&!native.has(c.name)).map(c=>({c,fame:Number(c.recruit[route].match(/(\d+)R/)?.[1])||Infinity})).sort((a,b)=>a.fame-b.fame||a.c.name.localeCompare(b.c.name,'zh-CN'));
}
function dietrichClassPath(path){return `<ol class="di-class-path" aria-label="第一部可选转职方向">${path.map(n=>`<li>${classChip(n)}</li>`).join('')}</ol>`;}
function dietrichPlan(n,compact=false){
  const c=routeCharacter(n.name);
  return `<article class="di-plan" ${n.fame?`data-fame="${n.fame}"`:''}><header><img src="${esc(c.avatar)}" alt="" loading="lazy"><div><small>${esc(n.arrival)}</small><h3>${esc(n.name)}</h3><span>${esc(n.role)}</span></div>${n.fame?`<b class="di-fame">${n.fame}<small>名声</small></b>`:''}</header>${n.fame?`<p class="di-requirement"><strong>名声 ${n.fame} · 支援 ${n.support}</strong><br>${esc(n.condition)}</p>`:''}<p class="di-why">${dietrichText(n.why)}</p>${dietrichClassPath(n.path)}<div class="di-training"><h4>培养重点</h4><p>${dietrichText(n.train)}</p></div><p class="di-limit"><strong>留意</strong> ${dietrichText(n.caution)}</p>${compact?'':`<details class="long-term"><summary>第三部再规划的转职</summary><p>${esc(n.late)}</p></details>`}<footer><button class="text-link" data-character="${esc(c.id)}">本线档案与礼物 ↗</button><a href="${href(n.sources[0].url)}" target="_blank" rel="noopener noreferrer">资料依据 ↗</a></footer></article>`;
}
function dietrichPortal(s){
  const p=s.profile.pilot,hero=routeCharacter('迪托利希'),recruits=dietrichRecruits();
  const sections=[['overview','刃鸣与战技强化'],['team','原生队伍怎么养'],['strength','早招募的培养收益'],['recruit','按名声挑选同伴'],['paralogues','外传与漏接提醒'],['classes','兵种选择与解锁'],['notes','推进前的检查'],...(p.publishBattles?[['battles','关卡打法附录']]:[])];
  return `<article class="route-portal di-pilot" data-theme="steel"><header class="route-hero"><div class="container route-hero-inner"><div class="route-hero-copy"><a class="route-back" href="#story">← 全部人物篇章</a><div class="eyebrow">DIETRICH · 第一部 / 拉弥努家族</div><h1>迪托利希篇<span>寻敌，磨剑。</span></h1><p>${esc(p.intro)}</p><div class="route-hero-tags"><span>刃鸣遭遇战</span><span>战技强化</span><span>低名声养成</span></div><a class="button gold" href="#route/dietrich/overview">看本篇独有玩法 <span>↓</span></a></div><div class="route-hero-art"><div class="route-ring" aria-hidden="true"></div><img src="${esc(hero.portrait)}" alt="迪托利希人物立绘"><span class="route-hero-name" aria-hidden="true">DIETRICH</span></div></div></header><div class="container"><nav class="route-switch" aria-label="切换人物篇章">${D.story.filter(x=>x.part===1).map(x=>`<a href="${storyLink(x)}" ${x.id==='dietrich'?'aria-current="page"':''}>${esc(x.title.replace('路线','篇'))} ↗</a>`).join('')}<a href="#story/war">第二部 · 战争篇 →</a></nav><div class="route-editorial"><nav class="route-toc" aria-label="本篇目录"><span class="eyebrow">DIETRICH’S FIELD NOTES</span>${sections.map(([id,label],i)=>`<a href="#route/dietrich/${id}" data-section="${id}"><span>0${i+1}</span>${label}</a>`).join('')}</nav><div class="route-content">
  <section id="overview" class="route-section">${routeSectionHead('01','HUNT & HONE',p.title)}<p class="route-lead">第 4 章，自由探索开放后，你可以主动找出地图上的敌人。遭遇战既能练同伴，也能攒强化材料；再回神殿，把常用战技的命中、威力或耐久消耗改善一点。</p>
  <figure class="di-feature"><a class="di-image" href="assets/dietrich/blade-sense.webp" target="_blank" rel="noopener" aria-label="放大刃鸣地图画面"><img src="assets/dietrich/blade-sense.webp" width="632" height="356" alt="刃鸣地图画面：右侧选中刃鸣，红色圆圈标示周围的索敌范围"><span>查看大图 ↗</span></a><figcaption><span class="di-kicker">01 / 在地图上找战斗</span><h3>圈出附近遭遇战，抓住两回合窗口</h3><p>选择「刃鸣」，附近地点就可能出现遭遇战。先看范围里有哪些格子、走过去要多久，再决定要追哪一场。</p><strong class="di-rule">出现后 2 个自由行动回合就会消失</strong><p>连续使用会缩小范围；经过回合，或出入据点、地宫后可恢复。不要为了追远处的敌人白跑。</p><small>日文版画面 · <a href="https://game8.jp/fe-banshisenko/817151" target="_blank" rel="noopener noreferrer">Game8 原图与说明 ↗</a></small></figcaption></figure>
  <ol class="di-loop" aria-label="刃鸣养成流程"><li><b>找敌</b><span>刃鸣圈出遭遇战</span></li><li><b>交锋</b><span>练队伍，收集魔响石</span></li><li><b>磨技</b><span>斯米尔诺斯神殿强化</span></li></ol>
  ${dietrichUpgradeGuide()}
  <figure class="di-feature di-feature-reverse"><a class="di-image" href="assets/dietrich/combat-art.webp" target="_blank" rel="noopener" aria-label="放大战技强化画面"><img src="assets/dietrich/combat-art.webp" width="880" height="495" alt="米迦艾拉的战技强化画面：命中加成从加10变为加15，耐久消耗仍为2" loading="lazy"><span>查看大图 ↗</span></a><figcaption><span class="di-kicker">02 / 把材料用在常用招式上</span><h3>同一招，更容易命中</h3><p>图中 ${dietrichPerson('米迦艾拉')} 的斧战技，强化前后对比很直观：</p><div class="di-stat"><span>命中加成 <b>+10 → +15</b></span><span>耐久消耗 <b>2 → 2</b></span></div><p>优先改善主力常用招式的短板。<strong>同名战技需要逐人强化</strong>，不是强化一次全队共享；先选角色，再确认收益。</p><small>日文版画面 · <a href="https://game8.jp/fe-banshisenko/817151" target="_blank" rel="noopener noreferrer">Game8 画面来源 ↗</a></small></figcaption></figure>${evidence(p.sources.filter(r=>/578847|577588|817667|817224/.test(r.url)))}</section>
  <section id="team" class="route-section">${routeSectionHead('02','THE STARTING COMPANY','剑、黑魔法与前排：先练好身边这五人','按本篇出现顺序认识队伍。箭头表示可选培养方向；考试条件满足时可调整，不要求逐个职业全部练满。')}<div class="di-team-strip">${p.native.map(n=>`<a href="#route/dietrich/member-${routeCharacter(n.name).id}"><img src="${esc(routeCharacter(n.name).avatar)}" alt=""><strong>${esc(n.name)}</strong><small>${esc(n.role)}</small></a>`).join('')}</div><div class="di-plans">${p.native.map(n=>`<div id="member-${routeCharacter(n.name).id}" class="di-anchor">${dietrichPlan(n)}</div>`).join('')}</div><p class="di-editor-note">兵种采用原手册已有的简体中文译名。中级、上级还受进度与考试资格限制；第三部目标单独折叠，不提前当作第一部成型要求。</p></section>
  <section id="strength" class="route-section">${routeSectionHead('03','RECRUIT EARLY, RAISE YOUR WAY','越早入队，越多成长由你安排')}<p class="route-lead">想长期培养的人，尽量在出现且条件达标后招进来。多出来的自由行动时间，可以用来练技能、换合适的兵种，也能让新同伴参加刃鸣遭遇战。</p><div class="di-growth"><div><span>尽早招募</span><h3>提前选兵种，自己练技能</h3><p>低名声门槛意味着更早着手的机会；若实际入队等级也低，后续由你安排的升级次数就更多。</p></div><div><span>拖到后期</span><h3>等级上涨，技能未必跟得上</h3><p>不能指望晚招的高等级角色，自动拥有同样充分的技能、精通和兵种成长。</p></div></div><p class="di-editor-note">玩家对比发现，未招募角色的高等级面板可能低于自行培养结果。但低名声不直接等于低入队等级，也不能据此算出固定的最终上限；还要看出现章节、实际招募时点和随机成长。本站不采用尚未证实的统一成长折扣公式。</p>${evidence(p.sources.filter(r=>/574062|tips02/.test(r.url)))}
  <div class="di-picks"><h3>这条线，训练资源先往哪里放？</h3><p>${dietrichPerson('迪托利希')} 与 ${dietrichPerson('法比奥')} 分别负责物理、魔法击杀；${dietrichPerson('艾丝梅拉尔达')} 承伤，${dietrichPerson('杨界')} 先保证回复。</p><p>想补机动，先看名声 3 的 ${dietrichPerson('伊欧')}；缺弓手，预备名声 4、但第 6 章才出现的 ${dietrichPerson('基罗伊卡')}。名声 5～6 再针对缺口补人，不需要把下面九位同时练满。</p><small>以上为本线资源分配建议，不是全角色强度排名。</small></div></section>
  <section id="recruit" class="route-section">${routeSectionHead('04','RENOWN & RECRUITMENT','从名声 3 开始，安排下一位同伴','招募门槛按名声从低到高排列。同门槛不代表同一章能加入，人物卡另列首次出现时点和交涉要求。')}${dietrichPyramid(recruits)}<div class="di-fame-nav"><a href="#route/dietrich/fame-low"><b>3—5</b><span>低门槛 · 先准备</span></a><a href="#route/dietrich/fame-mid"><b>6</b><span>中段 · 按缺口补</span></a><a href="#route/dietrich/fame-all"><b>3—10</b><span>展开完整条件表</span></a></div>
  <div id="fame-low" class="di-anchor"><h3 class="di-band">名声 3—5 <span>四位低门槛候选</span></h3><div class="di-plans">${p.scouts.filter(n=>n.fame<=5).map(n=>dietrichPlan(n)).join('')}</div></div><div id="fame-mid" class="di-anchor"><h3 class="di-band">名声 6 <span>机动、回复与物理补强</span></h3><div class="di-plans">${p.scouts.filter(n=>n.fame===6).map(n=>dietrichPlan(n)).join('')}</div></div>
  <details id="fame-all" class="all-recruits di-anchor"><summary>本线完整招募条件 · ${recruits.length} 位，按名声升序 <span>＋</span></summary><p class="notice">不含上方五位本线同伴。S＝支援等级，R＝名声等级。高门槛条目沿用已收录资料，未展开的交涉仍待核对；没有写明不表示无附加条件。</p><div class="route-recruit-list">${recruits.map(({c,fame})=>{const n=p.scouts.find(n=>n.name===c.name);return `<div data-recruit-fame="${fame}"><span class="di-list-fame">名声 ${fame}</span>${dietrichPerson(c.name)}<p>${n?`支援 ${n.support} · ${esc(n.condition)}<small>${esc(n.arrival)}</small>`:esc(c.recruit['迪托利希线'])}</p><span class="tag ${n?'green':''}">${n?'本线详页已核对':'继承条目'}</span></div>`;}).join('')}</div></details></section>
  ${paralogueSection(s.id)}${routeClassSection(s.id)}
  <section id="notes" class="route-section">${routeSectionHead('07','BEFORE THE NEXT CHAPTER','先查出现时间，再交物品与接任务')}<ol class="route-cautions"><li>${dietrichPerson('基罗伊卡')} 名声 4、支援 1，但第 6 章才出现。物品可以先备，不能靠提前冲名声让他提前登场。</li><li>${dietrichPerson('歌利亚')} 要巨人肉 ×3；${dietrichPerson('努蒂奴')} 在本线要青铜斧 ×2。不要把其他路线的材料要求套过来。</li><li>${dietrichPerson('奥林匹亚')} 与 ${dietrichPerson('杰斯特')} 都有三段请求。做完一段先回报，再接下一段；详细路线见人物卡内的交涉资料。</li><li>${dietrichPerson('米迦艾拉')} 的加入费用存在资料差异。到第 4 章时保留 3000G 余量，并以本次游戏的对话要求确认。</li><li>想在第二部收齐条件角色，要在第一部留意「亡妹的首饰」请求（来源原名「亡き妹の装身具」）。<a href="#story/war">查看第二部条件加入说明 →</a></li><li>外传中遇见另一位主角，不代表可以把主角招进本篇。外传接取窗口与完成期限也需要分别查看。</li></ol><a class="text-link" href="#guide/g6">路线切换与保留进度说明 ↗</a></section>
  ${p.publishBattles ? dietrichBattleAppendix(s) : ''}
  <div class="route-ending"><div><span class="eyebrow">PART II</span><h2>第一部结束后，继续培养这支队伍。</h2></div><a class="button" href="#story/war">第二部 · 战争篇 →</a></div></div></div></div></article>`;
}
function dietrichChineseBuild(b){
  const names={'ソードマスター':'刀剑将领','シドー':'侍道','剣士':'剑客','シャーマン':'萨满巫师','ウァテス':'先知','ドルイド':'德鲁伊','ヘヴィアーマー':'巨型重甲兵','フォートレス':'要塞','バトルマスター':'战斗将领','ブリガンド':'土匪','ウォーリアー':'勇士','バトルモンク':'武僧','ガーディアン':'卫士','ホーリーランサー':'圣枪师','プリースト':'牧师','祭司':'牧师','ビショップ':'主教','ワイズマン':'贤者','マスターアーチ':'宗师射手','騎甲駝兵':'骑甲驼兵','バーディンガー':'荣光骑士','オリハルディア':'奥利哈铁骑','シャドーシーカー':'探影者','聖天翼兵':'圣天翼兵','ハイエピタフ':'高阶墓志铭（暂译）','カラドリオス':'神鸵兵','マーズの依頼':'战神的委托'};
  return Object.fromEntries(Object.entries(b).map(([k,v])=>[k,typeof v==='string'?Object.entries(names).reduce((t,[jp,cn])=>t.replaceAll(jp,cn),v).replace(/刀剑将领（刀剑将领）|圣枪师（圣枪师）/g,m=>m.split('（')[0]):v]));
}
function showDietrichCharacter(id,routeId='dietrich'){
  const c=D.characters.find(c=>c.id===id);if(!c)return;
  const story=D.story.find(s=>s.id===routeId),route=story.title.replace('路线','线'),p=dietrichData(routeId),n=[...p.native,...p.scouts].find(n=>n.name===c.name),neg=c.negotiations;
  $('#character-dialog').innerHTML=`<button class="icon-btn" data-close="character-dialog" aria-label="关闭角色档案">×</button><div class="character-detail di-dossier"><div class="detail-art">${c.portrait?`<img src="${esc(c.portrait)}" alt="${esc(c.name)}立绘">`:''}</div><div class="detail-body"><div class="eyebrow">${esc(story.title.replace('路线','篇'))} · 本线人物档案</div><h2>${esc(c.name)}</h2><h3>本线加入条件</h3><p>${n?.fame?`名声 ${n.fame} · 支援 ${n.support}<br>${esc(n.condition)}`:esc(c.recruit[route]||'本线未收录')}</p>${n?`<p>${esc(n.arrival)}</p>`:''}${c.gifts['推荐礼物']&&c.gifts['推荐礼物']!=='—'?`<h3>推荐礼物</h3><p>${esc(c.gifts['推荐礼物'])}</p>`:''}${n?`${n.pyramid?`<p class="di-recommendation"><strong>${esc(n.pyramid.label)}</strong> · ${esc(n.pyramid.note)}</p>`:''}<h3>第一部培养方向</h3>${dietrichClassPath(n.path)}<p>${dietrichText(n.train)}</p><p class="notice">${dietrichText(n.caution)}</p><details class="long-term"><summary>第三部转职目标</summary><p>${esc(n.late)}</p></details>${evidence(n.sources)}`:c.builds?buildMarkup(dietrichChineseBuild(c.builds)):''}${neg&&neg.routes.includes(route)&&(!n||n.fame)?`<h3>交涉参考</h3><p>${esc(neg.byRoute?.[route]||neg.details)}</p>${evidence(neg.sources)}`:''}<a class="text-link" href="#characters?name=${encodeURIComponent(c.name)}" data-dismiss>查看各路线完整档案 →</a></div></div>`;
  openDialog('character-dialog');
}

function dietrichBattleAppendix(s){return `<section id="battles" class="route-section">${routeSectionHead('06','BATTLE APPENDIX','卡关时再翻：开局与第 11 章','关卡打法保留为附录；目前两篇站内笔记，其余章节提供参考链接。')}<div class="route-battle-grid">${s.battles.map(b=>`<details class="battle-note"><summary><span class="battle-number">${String(b.number).padStart(2,'0')}</span><span><small>第 ${b.number} 章</small><strong>${esc(b.title)}</strong></span><span class="expand-mark">＋</span></summary><div class="battle-body"><p class="battle-goal">${dietrichText(b.goal)}</p><h3>队伍安排</h3><p>${dietrichText(b.team)}</p><h3>推进顺序</h3><ol>${b.steps.map(x=>`<li>${dietrichText(x)}</li>`).join('')}</ol><div class="battle-watch"><strong>别漏掉</strong><p>${dietrichText(b.watch)}</p></div>${evidence(b.sources)}</div></details>`).join('')}</div><details class="route-chapter-links"><summary>全部 12 章参考索引 ↗</summary><div class="chapter-index"><div>${s.chapters.map(c=>`<a href="${href(c.url)}" target="_blank" rel="noopener noreferrer"><strong>第 ${c.number} 章 ↗</strong><small>${s.battles.some(b=>b.number===c.number)?'本站已有难点笔记':'外部攻略 · 本站待补'}</small></a>`).join('')}</div></div></details></section>`;}

function dietrichUpgradeGuide(){
  return `<div id="upgrade" class="di-upgrade di-anchor"><div class="di-upgrade-intro"><span class="di-kicker">本篇专属 · 第 4 章开放</span><h3>战技强化：给常用招式追加性能</h3><p>花费<strong>魔响石</strong>，强化某位角色已经会用的战技。不同招式的改善项不同：可能提高威力、命中或必杀，也可能降低武器耐久消耗。先看强化前后对比，再决定这一笔材料花给谁。</p></div><ol class="di-upgrade-steps"><li><b>1</b><div><h4>材料在哪：刃鸣遭遇战</h4><p>自由行动时在世界地图发动刃鸣，赶到出现敌人的地点并取胜，可取得魔响石。优先顺着委托路线打近处敌人；有余裕再在据点或地宫附近反复找战斗，出入后恢复索敌范围。</p><p>敌人出现后两回合消失。按剩余行动与队伍状态安排，不要为了攒石头错过任务期限。</p></div></li><li><b>2</b><div><h4>去哪强化：帝都上层的神殿</h4><nav class="di-location" aria-label="战技强化地点"><span>鞑古席翁</span><span>上层</span><strong>斯米尔诺斯神殿</strong><span>参殿者接待处</span></nav><p>和接待人员对话，选择「战技强化」。日文资料中的地点为「スミルノス神殿」，接待处为「参殿者受付」，方便对照下方画面。</p></div></li><li><b>3</b><div><h4>怎么操作：先选人，再选战技</h4><p>进入强化菜单 → 选要培养的角色 → 选可强化战技 → 核对所需魔响石与前后变化 → 确认强化。费用以选中战技的菜单为准，不是所有招式统一价格。</p><p><strong>同名战技要逐人强化。</strong>一位角色强化后，其他人不会自动获得同样收益。武器自带的固有战技不能按这套方式强化。</p></div></li></ol><figure class="di-temple"><a class="di-image" href="assets/dietrich/temple-desk.webp" target="_blank" rel="noopener" aria-label="放大神殿接待处与战技强化菜单"><img src="assets/dietrich/temple-desk.webp" width="1200" height="675" alt="斯米尔诺斯神殿接待人员，左侧菜单选中战技强化" loading="lazy"><span>查看大图 ↗</span></a><figcaption>找到这位接待人员，选择左侧的「战技强化」。日文版画面 · <a href="https://game8.jp/fe-banshisenko/817667" target="_blank" rel="noopener noreferrer">Game8 来源 ↗</a></figcaption></figure><div class="di-upgrade-priority"><h4>第一批材料，先花在什么地方？</h4><p><strong>常用却容易打空：</strong>优先看命中改善。<strong>强力但太耗武器：</strong>优先看耐久消耗降低。<strong>就差一点能击杀：</strong>再看威力提升。先集中在你真正出战的角色，不必把每个人的每一招都强化。</p><p>下图就是 ${dietrichPerson('米迦艾拉')} 的例子：命中加成从 +10 提高到 +15，耐久消耗保持 2。强化后的收益可直接在菜单里核对。</p></div></div>`;
}
function dietrichPyramid(recruits,routeId='dietrich'){
  const p=dietrichData(routeId);
  return `<section id="fame-pyramid" class="di-pyramid-section di-anchor" aria-labelledby="di-pyramid-title"><div class="di-pyramid-heading"><span class="di-kicker">RENOWN 02—10</span><h3 id="di-pyramid-title">本线招募金字塔</h3><p>每层列出<strong>从这一名声门槛开始</strong>可考虑的人物。升到更高名声后，低门槛人物仍可招募；还要满足支援、出现时间及交涉要求。</p></div><div class="di-pyramid-legend"><span><b>★ 优先推荐</b> · 补本线早中期缺口</span><span><b>◇ 按需补位</b> · 先看现有队伍</span><span>未标星不代表弱；不做缺少依据的评分。</span><a class="di-plan-link" href="#planner/${routeId}">在招募规划中勾选目标、汇总要备的物品 →</a></div><div class="di-pyramid" aria-label="按名声门槛从 2 到 10 分层的招募名单">${Array.from({length:9},(_,i)=>i+2).filter(level=>recruits.some(r=>r.fame===level)).map(level=>{const rows=recruits.filter(r=>r.fame===level);return `<section class="di-pyramid-tier" data-pyramid-level="${level}" style="--tier-width:${38+(level-2)*7.75}%"><header><h4>名声 <b>${level}</b></h4><span>${rows.length?rows.length+' 位':'无新增'}</span></header><div class="di-pyramid-people">${rows.length?rows.map(({c})=>{const n=p.scouts.find(n=>n.name===c.name),m=n?.pyramid;return `<button class="di-pyramid-person ${m?.priority==='priority'?'is-priority':''}" data-character="${esc(c.id)}" data-pyramid-character="${esc(c.id)}" aria-label="查看${esc(c.name)}本线档案${m?'，'+esc(m.label):''}">${c.avatar?`<img src="${esc(c.avatar)}" alt="" loading="lazy">`:`<span class="di-pyramid-initial" aria-hidden="true">${esc(c.name[0])}</span>`}<span><strong>${esc(c.name)}</strong><small>${esc(m?.role||c.builds?.role||'查看招募条件 ↗')}</small>${m?`<em>${m.priority==='priority'?'★':'◇'} ${esc(m.label)}</em>`:''}${c.name==='基罗伊卡'&&['dietrich','leda'].includes(routeId)?`<i>${routeId==='leda'?'按本线进度确认':'第 6 章出现'}</i>`:''}</span></button>`;}).join(''):`<p class="di-pyramid-empty">本层无额外招募对象；剧情与教学加入的 ${p.native.length} 位同伴另列上方。</p>`}</div></section>`;}).join('')}</div><p class="di-editor-note">层级宽度只区分名声门槛，不表示战力或人数。★ 是本站按加入成本、培养时间及队伍缺口给出的建议，点击人物查看理由和完整条件。</p></section>`;
}
