'use strict';
// In-game date per route (this browser only): which paralogues are open now, about to close, or still ahead.
const gameDateKey='fe-next.gamedate.v1';
function gameDates(){const d=load(gameDateKey,{});return d&&typeof d==='object'&&!Array.isArray(d)?d:{};}
function dayOfYear(md){const m=/^(\d{1,2})\/(\d{1,2})$/.exec(md||'');if(!m)return null;const mo=+m[1],d=+m[2];if(mo<1||mo>12||d<1||d>new Date(Date.UTC(2001,mo,0)).getUTCDate())return null;return Math.round((Date.UTC(2001,mo-1,d)-Date.UTC(2001,0,1))/864e5);}
function paralogueState(windows,today){
  const t=dayOfYear(today);if(t===null)return null;let next=null,past=null;
  for(const w of windows){const s=dayOfYear(w.start),e=dayOfYear(w.end),dl=dayOfYear(w.deadline);
    if(t>=s&&t<=e)return {state:e-t<=1?'closing':'open',days:e-t,w};
    if(t<s&&(!next||s-t<next.days))next={state:'upcoming',days:s-t,w};
    if(t>e&&(!past||e>dayOfYear(past.w.end)))past=dl!==null&&t<=dl?{state:'deadline',days:dl-t,w}:{state:'closed',days:0,w};}
  return next||past;
}
function paralogueLabel(st){
  const w=st.w;
  return {open:`可接取 · ${w.end} 截止（含今天还有 ${st.days+1} 天）`,closing:w.start===w.end?'仅今天可接':st.days===0?'今天是最后一天可接':'明天截止，尽快去接',upcoming:`${st.days} 天后开放（${w.start}，第 ${w.chapter} 章）`,deadline:`接取已截止 · 已接者须在 ${w.deadline} 前完成`,closed:'本线接取窗口已过'}[st.state];
}
function gameDateControl(routeId){
  const [m,d]=(gameDates()[routeId]||'/').split('/');
  return `<div class="gamedate" data-route="${routeId}"><span class="gamedate-label">我在本线的游戏日期</span><select data-gamedate="month" aria-label="游戏内月份"><option value="">月</option>${Array.from({length:12},(_,i)=>`<option ${String(i+1)===m?'selected':''}>${i+1}</option>`).join('')}</select><select data-gamedate="day" aria-label="游戏内日期"><option value="">日</option>${Array.from({length:31},(_,i)=>`<option ${String(i+1)===d?'selected':''}>${i+1}</option>`).join('')}</select><button class="text-link" data-gamedate-clear="${routeId}">清除</button><p class="gamedate-summary" aria-live="polite">填上本线游戏里的当前日期，每篇外传会标出可接、即将截止或还要等几天。只保存在这台设备的浏览器。</p></div>`;
}
function paralogueDigest(routeId,today){
  const rows=routeParalogues(routeId).map(p=>({p,st:paralogueState(p.routes[routeId],today)})).filter(x=>x.st);
  const count=k=>rows.filter(x=>x.st.state===k).length;
  return {rows,open:count('open')+count('closing'),closing:count('closing'),upcoming:rows.filter(x=>x.st.state==='upcoming'&&x.st.days<=7).length,closed:count('closed')};
}
function renderGameDate(routeId){
  const box=document.querySelector(`.gamedate[data-route="${routeId}"]`);if(!box)return;
  const today=gameDates()[routeId],dg=today&&paralogueDigest(routeId,today);
  for(const p of routeParalogues(routeId)){const el=document.querySelector(`[data-status-for="${p.id}"]`);if(!el)continue;const st=today&&paralogueState(p.routes[routeId],today);el.hidden=!st;el.className='paralogue-status'+(st?' is-'+st.state:'');el.textContent=st?paralogueLabel(st):'';el.closest('.paralogue-card')?.classList.toggle('is-past',st?.state==='closed');}
  const gantt=document.querySelector(`[data-gantt="${routeId}"]`);if(gantt)gantt.outerHTML=paralogueGantt(routeId);
  box.querySelector('.gamedate-summary').textContent=dg?`${today}：可接 ${dg.open} 篇${dg.closing?`（${dg.closing} 篇今明两天截止）`:''}，7 天内开放 ${dg.upcoming} 篇，已过 ${dg.closed} 篇。`:'填上本线游戏里的当前日期，每篇外传会标出可接、即将截止或还要等几天。只保存在这台设备的浏览器。';
}
// Window overview above the cards: one row per paralogue, solid = accept window, dashed = time left to finish
// after the window closes (only where a source gives the deadline), and a line for the saved in-game date.
function paralogueGantt(routeId){
  const rows=routeParalogues(routeId),today=gameDates()[routeId],t=dayOfYear(today),md=n=>{const d=new Date(Date.UTC(2001,0,1+n));return `${d.getUTCMonth()+1}/${d.getUTCDate()}`;};
  const days=rows.flatMap(p=>p.routes[routeId].flatMap(w=>[w.start,w.end,w.deadline].filter(Boolean).map(dayOfYear)));
  let a=Math.min(...days)-2,b=Math.max(...days)+2;const near=t!==null&&t>=a-21&&t<=b+21;if(near){a=Math.min(a,t-1);b=Math.max(b,t+1);}
  const x=n=>((n-a)/(b-a)*100).toFixed(2)+'%',w=(s,e)=>((e-s+1)/(b-a)*100).toFixed(2)+'%';
  const ticks=[];for(let n=a;n<=b;n++){const d=+md(n).split('/')[1];if([1,10,20].includes(d))ticks.push(n);}
  const row=p=>{const ws=p.routes[routeId],st=t!==null&&paralogueState(ws,today);
    const say=ws.map(v=>`第${v.chapter}章 ${v.start===v.end?v.start+' 当天':v.start+'—'+v.end} 可接取，完成期限${v.deadline||'来源未单列'}`).join('；');
    // A window that reopens later: the dashed stretch stops where the next window begins.
    const bars=ws.map((v,i)=>{const s=dayOfYear(v.start),e=dayOfYear(v.end),next=ws[i+1]?dayOfYear(ws[i+1].start)-1:Infinity,dl=Math.min(dayOfYear(v.deadline)??-1,next);return `<span class="pg-win${s===e?' is-day':''}" style="left:${x(s)};width:${w(s,e)}"></span>${dl>e?`<span class="pg-due" style="left:${x(e+1)};width:${w(e+1,dl)}"></span>`:''}`;}).join('');
    return `<li class="${st?'is-'+st.state:''}"><button class="pg-label" data-scroll="para-${p.id}" aria-label="${esc(p.person)}外传：${esc(say)}。跳到详情" title="${esc(say)}">${esc(p.person)}</button><div class="pg-track">${bars}</div></li>`;};
  const mark=t===null?'':near?`<div class="pg-today" style="left:${x(t)}"><span>今天 ${esc(today)}</span></div>`:'';
  return `<figure class="pg" data-gantt="${routeId}"><figcaption><strong>接取窗口一览</strong><span><i class="pg-key"></i>可接取<i class="pg-key due"></i>窗口关闭后、完成期限前</span></figcaption><div class="pg-body"><div class="pg-axis" aria-hidden="true">${ticks.map(n=>`<span style="left:${x(n)}">${md(n)}</span>`).join('')}</div><ol class="pg-rows">${rows.map(row).join('')}</ol><div class="pg-grid" aria-hidden="true">${ticks.map(n=>`<i style="left:${x(n)}"></i>`).join('')}${mark}</div></div>${t!==null&&!near?`<p class="pg-note">游戏日期 ${esc(today)} 不在本线外传的日期范围内。</p>`:''}</figure>`;
}
function setGameDate(routeId,value){const all=gameDates();if(value)all[routeId]=value;else delete all[routeId];save(gameDateKey,all);renderGameDate(routeId);}
function routeParalogues(id){return D.paralogues.filter(p=>p.routes[id]).sort((a,b)=>{const date=x=>{const [m,d]=x.routes[id][0].start.split('/').map(Number);return m*100+d;};return date(a)-date(b);});}
function paralogueSection(routeId){
 const rows=routeParalogues(routeId),urgent=rows.filter(p=>p.routes[routeId].some(w=>w.start===w.end||p.id==='orhel'&&routeId==='kai'));
 return `<section id="paralogues" class="route-section">${routeSectionHead('05','PARALOGUE CALENDAR',`${({kai:'第10—11章',dietrich:'第9—11章',theodora:'第10—12章',leda:'第10—11章'})[routeId]} · ${rows.length}篇外传日历`,'只列本篇能接的外传，按首次开放日期排列。日期均为游戏内1449年；接取窗口结束后，即使完成期限未到，也可能接不到任务。')}<div class="paralogue-intro"><b>${rows.length}<small>本篇外传</small></b><p>每篇基本奖励均含 <strong>20,000G ＋ 名声150</strong>，另有下列道具。完成外传只满足部分招募条件，不会自动招来相关人物。第三部的条件加入另行标注。</p></div>${gameDateControl(routeId)}${paralogueGantt(routeId)}${urgent.map(p=>`<p class="paralogue-alert"><strong>短窗口提醒 · ${esc(p.person)}外传</strong> ${p.routes[routeId][0].start===p.routes[routeId][0].end?'仅9月17日可接，推进当天前先去大斗技场。':'10月18—19日可接，别把10月21日的完成期限当成接取期限。'}</p>`).join('')}<div class="paralogue-timeline">${rows.map(p=>`<article class="paralogue-card" id="para-${p.id}" data-paralogue="${p.id}"><header><span class="paralogue-date">${esc(p.routes[routeId][0].start)}<small>开始接取</small></span><div><span class="di-kicker">${esc(p.person)}外传</span><h3>${esc(p.title)}</h3></div>${routeCharacter(p.person)?.avatar?`<img src="${esc(routeCharacter(p.person).avatar)}" alt="${esc(p.person)}" loading="lazy">`:''}</header><p class="paralogue-status" data-status-for="${p.id}" hidden></p><div class="paralogue-windows">${p.routes[routeId].map(w=>`<div><span>第 ${esc(w.chapter)} 章</span><p><small>可接取</small><strong>${esc(w.start===w.end?w.start+'（仅当天）':w.start+'—'+w.end)}</strong></p><p><small>完成期限</small><strong>${esc(w.deadline||'来源未单列')}</strong></p></div>`).join('')}</div><p class="paralogue-place"><b>去哪里接</b> ${esc(p.place)}</p><p class="paralogue-impact">${dietrichText(p.consequence)}</p><div class="paralogue-reward"><span>道具奖励</span><strong>${esc(p.reward)}</strong></div><details><summary>${p.strategy?.length?'打法、接取提醒与资料来源':'接取提醒与资料来源'}</summary><p>${esc(p.steps)}</p>${p.strategy?.length?`<ol>${p.strategy.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>`:''}${p.routes[routeId].some(w=>!w.deadline)?'<p class="notice">来源未单列完成期限的条目，不推定它等于接取末日。接到后查看游戏任务栏，并尽早完成。</p>':''}<p>窗口按腾讯共创表核对；完成期限由单篇攻略补充。标题为本站中文整理，便于识别任务人物。</p>${evidence(p.sources)}</details></article>`).join('')}</div><p class="di-editor-note">错过时可考虑在方尖塔之间重玩对应章节；重玩仍有流程成本，建议提前留档。<a href="#guide/g6">查看路线与进度说明 →</a></p></section>`;
}
function findClass(name){return D.classes.find(c=>c.name===name||c.aliases.includes(name));}
function classIcon(c,size=20){return c.icon?`<img class="class-icon" src="${esc(c.icon)}" alt="" width="${size}" height="${size}" loading="lazy">`:'';}
function classChip(name){const c=findClass(name);return c?`<button class="class-chip" data-class="${c.id}" aria-label="查看${esc(c.name)}兵种资料">${classIcon(c)}${esc(c.name)}<span aria-hidden="true"> ↗</span></button>`:esc(name);}
const classRoutePicks={
 kai:[['先养坐骑队，再补远射',['荣光骑士','森林骑士'],'凯伊沿枪术与马术推进；彼得可以先走狙击手，等需要机动时再投入马术。捕到坐骑不代表全员都要立刻转骑兵。'],['把指导解锁变成选择',['神鸵兵','驭龙兵','游唱诗人'],'卡司托尔、奥罗拉、贝特朗的指导分别关联特殊职业。先看现有角色的技能底子，再决定追哪项解锁。']],
 dietrich:[['剑与魔法先形成双核心',['侍道','先知'],'迪托利希优先剑术，法比奥优先黑魔术。战技强化集中给实际常用的招式，先看命中与耐久收益。'],['守线与续航不能断',['巨型重甲兵','主教','卫士'],'艾丝梅拉尔达承担正面，杨界保障回复。卫士另有解锁条件，可以作为枪系支援选择，不必为了转职打散既有分工。']],
 theodora:[['前排站稳，后排解决敌人',['巨型重甲兵','先知','狙击手'],'女王与重装位保护阵形；波拿帕尔特和莉利安分别练魔法与弓。军团加成按各自职能配，不必把同一种职业塞满队伍。'],['再用战备解锁补机动',['驭龙兵','重装骑兵','卫士'],'这些职业与本篇战备增援有关。先核对解锁条目与所需技能，再决定是增加飞行、骑乘承伤，还是枪系回复。']],
 leda:[['把一次行动交给最需要的人',['舞者','游唱诗人'],'第9章起留意舞者继承支线；酒馆兴行还关联游唱诗人。蕾达转舞者之后，优先考虑让谁再行动，别只比较她自己的伤害。'],['输出与回复由同伴接住',['侍道','巨型重甲兵','主教'],'穆负责物理击杀，巴卡尼亚守线，奥林匹亚照看回复。剑位不必全部主练，保留资源给队伍欠缺的远程或魔法。']]
};
function routeClassSection(id){return `<section id="classes" class="route-section">${routeSectionHead('06','CLASS & ROLE',`${D.story.find(s=>s.id===id).title.replace('路线','篇')}的兵种选择`,'人物卡里的兵种名称现在可以点击。查看备考技能、特殊解锁与精通，再决定要不要绕路练。')}<div class="class-route-picks">${classRoutePicks[id].map(([title,names,body])=>`<article><h3>${title}</h3><div class="class-chip-row">${names.map(classChip).join('')}</div><p>${dietrichText(body)}</p></article>`).join('')}</div><p class="notice">这些是本线选职建议，不是固定转职链。最上级、神将放到第三部规划；在其他路线解锁过的资格，也要以当前存档考试列表为准。</p><a href="#classes" class="button secondary">兵种资料库 · 按阶段与职能查找 →</a></section>`;}
function classAdvice(c){return c.recommendation?`<div class="class-advice"><span class="di-kicker">本站选职建议</span><h3>${esc(c.recommendation.role)}</h3><p><b>适合谁</b> ${dietrichText(c.recommendation.forWhom)}</p><p><b>为什么选</b> ${esc(c.recommendation.reason)}</p><p><b>取舍</b> ${esc(c.recommendation.tradeoff)}</p></div>`:'';}
function classDetail(c){return `<div class="class-detail"><div class="class-detail-head">${classIcon(c,72)}<div><div class="eyebrow">${esc(c.tier)} · 兵种资料</div><h2 id="class-title">${esc(c.name)}</h2></div></div><p class="class-phase">${esc(c.phase)}</p>${c.restriction?`<p class="notice">${esc(c.restriction)}</p>`:''}<dl class="class-facts"><div><dt>移动</dt><dd>${esc(c.movement)}</dd></div><div><dt>${c.tier==='神将'?'神将考试要求':'备考技能参考'}</dt><dd>${esc(c.exam)}</dd></div><div><dt>特殊解锁</dt><dd>${esc(c.unlock||'需先开放该阶段考试；额外任务尚未收录。')}</dd></div><div><dt>技能经验加成</dt><dd>${esc(c.training)}</dd></div><div><dt>任职特性</dt><dd>${esc(c.features)}</dd></div><div><dt>精通所得</dt><dd>${esc(c.mastery)}</dd></div></dl><p class="di-editor-note">共创表采用推荐考试技能；普通考试仍以当前菜单的通过率、票证和条件为准。任职特性随兵种变化，精通所得需完成精通后再检查可装备项。</p>${classAdvice(c)}${evidence(c.sources)}<a href="#classes" data-dismiss class="text-link">查找其他兵种 →</a></div>`;}
function showClass(id){const c=D.classes.find(c=>c.id===id);if(!c)return;$('#class-dialog').innerHTML=`<button class="icon-btn" data-close="class-dialog" aria-label="关闭兵种资料">×</button>${classDetail(c)}`;openDialog('class-dialog');}
function classLibrary(){return `<div class="container page class-library">${heading('CLASS FIELD GUIDE','兵种资料与选职','先看队伍缺什么，再看能考什么。已收录54种兵种的备考、解锁与精通，更多资料持续校对。')}<div class="class-principles"><article><span>01 / 分工</span><h2>主武器优先，补上队伍缺口</h2><p>剑、斧、弓、魔法先满足伤害分工，再决定是否追加马术、飞行或重装。让一名同伴补缺口，比全队追同一职业更省训练。</p></article><article><span>02 / 精通</span><h2>精通过渡与长期上阵</h2><p>想要精通所得，可以安排阶段性练习；长期上阵则看移动、特性、可用技能与角色本身。不是每条推荐路径都要逐个练满。</p></article><article><span>03 / 解锁</span><h2>最上级与神将留到第三部</h2><p>最上级在第三部第二区分起，神将在第四区分起。特殊职业还关联指导、挑战书、战备增援、兴行或神殿委托。</p></article></div><div class="class-filters"><label>搜索兵种或特技<input id="class-query" type="search" placeholder="例如：开锁、白魔术、侍道"></label><label>阶段<select id="class-tier"><option value="">全部阶段</option>${[...new Set(D.classes.map(c=>c.tier))].map(t=>`<option>${esc(t)}</option>`).join('')}</select></label><label>职能<select id="class-role"><option value="">全部职能</option><option value="弓">弓系</option><option value="黑魔">黑魔术</option><option value="白魔">回复与白魔术</option><option value="骑兵">骑乘</option><option value="飞行">飞行</option><option value="重装">重装</option><option value="开锁">开锁探索</option></select></label></div><p id="class-count" aria-live="polite"></p><div id="class-results" class="class-ladder"></div><p class="di-editor-note">基础数据来自腾讯共创表的站内收录，2026-09-29复核部分条件并用单篇资料补充。未收录兵种、数值差异与完整成长率仍需继续校对。<a href="https://docs.qq.com/sheet/DV0N0VUZLSXRmUWFq" target="_blank" rel="noopener noreferrer">查看共创原表 ↗</a></p></div>`;}
const classTiers=['基础','初级','中级','上级与高级','最上级','神将'];
function classTile(c,phase){const family=c.features.split('，')[0],exam=c.exam.split('，')[0];return `<button class="class-tile" data-class="${c.id}" aria-label="查看${esc(c.name)}兵种资料">${classIcon(c,52)}<span><strong>${esc(c.name)}</strong><small>移动 ${esc(c.movement)} · ${esc(family)}</small>${exam!=='不适用'?`<small class="class-tile-exam">考：${esc(exam)}</small>`:''}${c.recommendation||c.restriction||c.phase!==phase?`<span class="class-tile-tags">${c.recommendation?`<em>建议 · ${esc(c.recommendation.role)}</em>`:''}${c.restriction?`<em class="is-limit">${esc(c.restriction.replace(/。$/,''))}</em>`:''}${c.phase!==phase?`<em class="is-limit">${esc(c.phase)}</em>`:''}</span>`:''}</span></button>`;}
function filterClasses(){const q=($('#class-query')?.value||'').trim().toLowerCase(),tier=$('#class-tier')?.value||'',role=$('#class-role')?.value||'';const rows=D.classes.filter(c=>(!tier||c.tier===tier)&&(!q||JSON.stringify(c).toLowerCase().includes(q))&&(!role||[c.features,c.training,c.exam].join(' ').includes(role)));$('#class-count').textContent=`找到 ${rows.length} 种兵种`;
 $('#class-results').innerHTML=rows.length?classTiers.concat([...new Set(rows.map(c=>c.tier))].filter(t=>!classTiers.includes(t))).map(t=>{const all=D.classes.filter(c=>c.tier===t),group=rows.filter(c=>c.tier===t);if(!group.length)return '';const phases=all.map(c=>c.phase),phase=phases.sort((a,b)=>phases.filter(x=>x===b).length-phases.filter(x=>x===a).length)[0];return `<section class="class-tier"><header><h2>${esc(t)}</h2><span>${group.length} 种</span><p>${esc(phase)}</p></header><div class="class-tiles">${group.map(c=>classTile(c,phase)).join('')}</div></section>`;}).join(''):'<p class="notice">没有符合条件的兵种。试试减少筛选条件。</p>';}
